apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: tapworkshop-operators
spec:
  title: TAP Workshop - Operators
  description: An introduction to the Tanzu Application Platform for Operators
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/Tanzu-Solutions-Engineering/TAP-WORKSHOP-OPERATORS
  content:
     files: github.com/Tanzu-Solutions-Engineering/TAP-WORKSHOP-OPERATORS?ref=main
     image: ghcr.io/dkhopade/tapworkshopimageoperators:v14
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
